name = "RoutePlanner"
__version__ = "0.0.2"
__description__ = "RoutePlanner: Optimal Route Planner for SDA"
__license__ = "MIT"
__author__ = "Maria Fox, James Byrne, Jonathan Smith, Samuel Hall, George Coombs"
__email__ = "jonsmi@bas.ac.uk"